yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('', views.index, name='index'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='create'),
    path('posts/<post_id>/edit/', views.post_edit, name='edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
# Эти строки — в самый конец файла:
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField(verbose_name="Текст поста")
    pub_date = models.DateTimeField(
        "Дата публикации",
        auto_now_add=True,
        db_index=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name="Группа",
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta():
        ordering = ['-pub_date']


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор')
    text = models.TextField('Коментарий')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Создан')
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Обновлен')
    active = models.BooleanField(
        default=True,
        verbose_name='Активен')

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Коментарии'
        verbose_name = 'Коментарий'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'image': 'Картинка',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_text = {
            'text': 'Текст вашего комментария',
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from posts.models import Group, Post, Follow, User
from posts.forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse

NUM_POSTS = 10


def index(request):
    posts_on_page = Post.objects.all()
    paginator = Paginator(posts_on_page, NUM_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_on_page = Post.objects.filter(group=group)
    paginator = Paginator(posts_on_page, NUM_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_on_page = Post.objects.filter(author=author)
    paginator = Paginator(posts_on_page, NUM_POSTS)
    page_number = request.GET.get('page')
    posts_count = Post.objects.filter(author=author).count()
    page_obj = paginator.get_page(page_number)
    user_is_not_author = (request.user != author)
    following = (request.user.is_authenticated
                 and Follow.objects.filter(user=request.user,
                                           author=author).exists()
                 )
    template = 'posts/profile.html'
    context = {'page_obj': page_obj,
               'author': author,
               'posts_count': posts_count,
               'following': following,
               'user_is_not_author': user_is_not_author,
               }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    posts_count = Post.objects.filter(author=post.author).count()
    comments = post.comments.all()
    form = CommentForm()
    template = 'posts/post_detail.html'
    context = {
        'post': post,
        'posts_count': posts_count,
        'requser': request.user,
        'comments': comments,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        create_post = form.save(commit=False)
        create_post.author = request.user
        create_post.save()
        return redirect('posts:profile', create_post.author)
    template = 'posts/create_post.html'
    context = {'form': form}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    edit_post = get_object_or_404(Post, id=post_id)
    if request.user != edit_post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=edit_post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    template = 'posts/create_post.html'
    context = {'form': form, 'is_edit': True}
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    # Получите пост и сохраните его в переменную post.
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    list_of_posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(list_of_posts, NUM_POSTS)
    page_namber = request.GET.get('page')
    page_obj = paginator.get_page(page_namber)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = User.objects.get(username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}Новый пост{% endblock %}
{% block content %}
<div class="row justify-content-center">
<div class="col-md-8 p-5">
  <div class="card">
    <div class="card-header">{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}</div>
    <div class="card-body">
        {% include 'includes/form.html' %}
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">{% if is_edit %}Сохранить{% else %}Добавить{% endif %}</button>
        </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Подписки{% endblock %}
{% block content %}
{% include 'includes/switcher.html' with follow=True %}
{% for post in page_obj %}
    <ul class="list-group">
    <li class="list-group-item list-group-item-light">
      Автор: <a href="{% url 'posts:profile' post.author %}">
        {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
      </a>
    </li>
    <li class="list-group-item list-group-item-light">
      Дата публикации: <strong>{{ post.pub_date|date:'d E Y' }}</strong>
    </li>
    </ul>
<div class="card bg-light" style="width: 100%">
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img-top" src="{{ im.url }}">
  {% endthumbnail %}
  <div class="card-body">
    <h4 class="card-title">Заголовок</h4>
    <p class="card-text">
      {{ post.text|linebreaksbr }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Подробная информация</a>  
    {% if post.group %}
      <a href="{% url 'posts:group_posts' post.group.slug %}" class="btn btn-primary">Все записи группы "{{ post.group }}"</a>
    {% endif %}
  </div>
</div>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
    {% include 'includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  <h1> {{group.title}} </h1>
{% endblock %}
{% block content %}
  <div class="container py-5">
    {% block header %}
    <h1>Группа: {{group.title}}</h1>
    <p>{{group.description}}</p>
    {% endblock %}
    <article>
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{post.author.get_full_name}}
        </li>
        <li>
          Дата публикации: {{post.pub_date|date:"d E Y"}}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p> {{post.text}} </p>
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{{ text }}
{% endblock %}
{% block content %}
<div class="container py-5">
<h1>Последние обновления на сайте</h1>
<article>
  {% load cache %}
  {% include "includes/switcher.html" %}
  {% cache 20 index_page %}
  {% for post in page_obj %}
  <ul>
    <li>
      <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
        <strong class="d-block text-gray-dark">{{ post.author }}</strong>
      </a>
    </li>
    <li>
      Дата публикации: {{post.pub_date|date:"d E Y"}}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{post.text}}</p>
  {% if post.group %} 
  <li>  
    <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
  </li>
  {% endif %}
  <li>
    <a href="{% url 'posts:post_detail' post.id%}">подробнее</a>
  </li>
  {% if not forloop.last %}<hr>{% endif%}
  {%endfor%}
  {% endcache %}
  {% include 'includes/paginator.html' %}
</article>
<!-- под последним постом нет линии -->
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}Пост {{ post|truncatechars:30 }}{% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
      </li>
      <li class="list-group-item">
        Группа:
        {% if post.group %}
        {{ post.group }}
        {% else %}
        ---Пусто---
        {% endif %}
        {% if post.group %}
          <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
      </li>
      <li class="list-group-item">
        Всего постов автора: {{ posts_count }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post }}</p>
    {% if post.author == requser %}
    <a class="btn btn-primary" href="{% url 'posts:edit' post.id %}">редактировать запись</a>
    {% endif %}
  </article>
  <!-- Форма добавления комментария -->


{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    {% if author.get_full_name %}
        {{ author.get_full_name }}
    {% else %}
        {{ author }}
    {% endif %} профайл пользователя
{% endblock %}
{% block content %}
<div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ posts_count }}</h3>
    {% if following %}
      <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">
        Отписаться
      </a>
    {% else %}
    {% if user_is_not_author %}
    <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">
      Подписаться
    </a>
    {% endif %}
     {% endif %}
</div>
{% for post in page_obj %}
    <ul>
        <li>
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    <br>
    {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
    <div>{% include 'includes/paginator.html' %}</div>
</div>
{% endblock %}